In [4]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
!pip install matplotlib seaborn

Requirement already satisfied: matplotlib in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (3.10.6)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\itcs\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import pandas as pd
s = pd.Series([19,23,45])
print(s)

0    19
1    23
2    45
dtype: int64

# create series

In [17]:
s = pd.Series([100,20], index = ['a','b'])
print(s)
s['b']

a    100
b     20
dtype: int64

np.int64(20)

# data frame pandas

In [62]:
data = { 'name' : ['arya', 'parth','neelam'],
         'salarry' : [10000,21342,3453256],
         'city' : [12,34,55] }
df = pd.DataFrame(data)
print(df)

     name  salarry  city
0    arya    10000    12
1   parth    21342    34
2  neelam  3453256    55

In [31]:
s = df.to_csv('outpu.scv' , index = False)

In [88]:
df = pd.read_csv('recharge_data.csv')
df

,CustomerID,Name,Region,City,Plan,Amount,MonthlyUsage,Complaints,Recharged,Marks,Grade,Days_Since_Last_Recharge,Complaint_Type
0,101.0,Arya,Pune,Pune,Prepaid,250.0,320.0,Yes,Yes,85.0,A,12.0,Network Issue
1,102.0,Ravi,Delhi,Delhi,Postpaid,600.0,450.0,No,Yes,92.0,A+,8.0,Recharge Failed
2,103.0,Meera,Mumbai,Mumbai,Prepaid,150.0,210.0,No,No,78.0,B,45.0,Slow Internet
3,104.0,Kiran,Chennai,Chennai,Postpaid,450.0,500.0,Yes,Yes,88.0,A,3.0,SIM Not Working
4,105.0,Lina,Pune,Pune,Prepaid,300.0,330.0,No,Yes,90.0,A+,14.0,Network Issue
5,106.0,Soham,Delhi,Delhi,Prepaid,200.0,180.0,No,No,76.0,B,33.0,Billing Error
6,107.0,Riya,Kolkata,Kolkata,Postpaid,500.0,400.0,Yes,Yes,82.0,A,5.0,Network Issue
7,108.0,Rohan,Mumbai,Mumbai,Postpaid,400.0,390.0,No,Yes,87.0,A,25.0,Slow Internet
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
 df.to_csv('practice.csv' , index = False)

In [36]:
df.head()

,CustomerID,Name,Region,City,Plan,Amount,MonthlyUsage,Complaints,Recharged,Marks,Grade,Days_Since_Last_Recharge,Complaint_Type
0,101.0,Arya,Pune,Pune,Prepaid,250.0,320.0,Yes,Yes,85.0,A,12.0,Network Issue
1,102.0,Ravi,Delhi,Delhi,Postpaid,600.0,450.0,No,Yes,92.0,A+,8.0,Recharge Failed
2,103.0,Meera,Mumbai,Mumbai,Prepaid,150.0,210.0,No,No,78.0,B,45.0,Slow Internet
3,104.0,Kiran,Chennai,Chennai,Postpaid,450.0,500.0,Yes,Yes,88.0,A,3.0,SIM Not Working
4,105.0,Lina,Pune,Pune,Prepaid,300.0,330.0,No,Yes,90.0,A+,14.0,Network Issue

In [37]:
df.tail()

,CustomerID,Name,Region,City,Plan,Amount,MonthlyUsage,Complaints,Recharged,Marks,Grade,Days_Since_Last_Recharge,Complaint_Type
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df.shape

(19, 13)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                8 non-null      float64
 1   Name                      8 non-null      object
 2   Region                    8 non-null      object
 3   City                      8 non-null      object
 4   Plan                      8 non-null      object
 5   Amount                    8 non-null      float64
 6   MonthlyUsage              8 non-null      float64
 7   Complaints                8 non-null      object
 8   Recharged                 8 non-null      object
 9   Marks                     8 non-null      float64
 10  Grade                     8 non-null      object
 11  Days_Since_Last_Recharge  8 non-null      float64
 12  Complaint_Type            8 non-null      object
dtypes: float64(5), object(8)
memory usage: 2.1+ KB

In [44]:
df.describe()

,CustomerID,Amount,MonthlyUsage,Marks,Days_Since_Last_Recharge
count,8.00000,8.000000,8.000000,8.000000,8.000000
mean,104.50000,356.250000,347.500000,84.750000,18.125000
std,2.44949,156.838179,111.066261,5.675763,14.875075
min,101.00000,150.000000,180.000000,76.000000,3.000000
25%,102.75000,237.500000,292.500000,81.000000,7.250000
50%,104.50000,350.000000,360.000000,86.000000,13.000000
75%,106.25000,462.500000,412.500000,88.500000,27.000000
max,108.00000,600.000000,500.000000,92.000000,45.000000

In [45]:
df['Amount']

0     250.0
1     600.0
2     150.0
3     450.0
4     300.0
5     200.0
6     500.0
7     400.0
8       NaN
9       NaN
10      NaN
11      NaN
12      NaN
13      NaN
14      NaN
15      NaN
16      NaN
17      NaN
18      NaN
Name: Amount, dtype: float64

# access two column in data

In [47]:
df[['Amount', 'CustomerID']]

    Amount  CustomerID
0    250.0       101.0
1    600.0       102.0
2    150.0       103.0
3    450.0       104.0
4    300.0       105.0
5    200.0       106.0
6    500.0       107.0
7    400.0       108.0
8      NaN         NaN
9      NaN         NaN
10     NaN         NaN
11     NaN         NaN
12     NaN         NaN
13     NaN         NaN
14     NaN         NaN
15     NaN         NaN
16     NaN         NaN
17     NaN         NaN
18     NaN         NaN

# row by label

In [48]:
df.loc[1]

CustomerID                            102.0
Name                                   Ravi
Region                                Delhi
City                                  Delhi
Plan                               Postpaid
Amount                                600.0
MonthlyUsage                          450.0
Complaints                               No
Recharged                               Yes
Marks                                  92.0
Grade                                    A+
Days_Since_Last_Recharge                8.0
Complaint_Type              Recharge Failed
Name: 1, dtype: object

# row by indexs

In [53]:
df.iloc[1:4]

,CustomerID,Name,Region,City,Plan,Amount,MonthlyUsage,Complaints,Recharged,Marks,Grade,Days_Since_Last_Recharge,Complaint_Type
1,102.0,Ravi,Delhi,Delhi,Postpaid,600.0,450.0,No,Yes,92.0,A+,8.0,Recharge Failed
2,103.0,Meera,Mumbai,Mumbai,Prepaid,150.0,210.0,No,No,78.0,B,45.0,Slow Internet
3,104.0,Kiran,Chennai,Chennai,Postpaid,450.0,500.0,Yes,Yes,88.0,A,3.0,SIM Not Working

# conditional filtering

In [60]:
df[df['Amount'] > 200]

,CustomerID,Name,Region,City,Plan,Amount,MonthlyUsage,Complaints,Recharged,Marks,Grade,Days_Since_Last_Recharge,Complaint_Type
0,101.0,Arya,Pune,Pune,Prepaid,250.0,320.0,Yes,Yes,85.0,A,12.0,Network Issue
1,102.0,Ravi,Delhi,Delhi,Postpaid,600.0,450.0,No,Yes,92.0,A+,8.0,Recharge Failed
3,104.0,Kiran,Chennai,Chennai,Postpaid,450.0,500.0,Yes,Yes,88.0,A,3.0,SIM Not Working
4,105.0,Lina,Pune,Pune,Prepaid,300.0,330.0,No,Yes,90.0,A+,14.0,Network Issue
6,107.0,Riya,Kolkata,Kolkata,Postpaid,500.0,400.0,Yes,Yes,82.0,A,5.0,Network Issue
7,108.0,Rohan,Mumbai,Mumbai,Postpaid,400.0,390.0,No,Yes,87.0,A,25.0,Slow Internet

In [61]:
df[(df['City'] == 'Mumbai') & (df['Amount'] > 200)]

,CustomerID,Name,Region,City,Plan,Amount,MonthlyUsage,Complaints,Recharged,Marks,Grade,Days_Since_Last_Recharge,Complaint_Type
7,108.0,Rohan,Mumbai,Mumbai,Postpaid,400.0,390.0,No,Yes,87.0,A,25.0,Slow Internet

In [63]:
df1 = df.copy()
df1

     name  salarry  city
0    arya    10000    12
1   parth    21342    34
2  neelam  3453256    55

# add new column to data

In [65]:
df1['grades'] =(['a','b','c'])
df1

     name  salarry  city grades
0    arya    10000    12      a
1   parth    21342    34      b
2  neelam  3453256    55      c

# delet row from column

In [68]:

del df1['grades']
df1

     name  salarry
0    arya    10000
1   parth    21342
2  neelam  3453256

In [69]:
df1['grades'] =(['a','b','c'])
df1

     name  salarry grades
0    arya    10000      a
1   parth    21342      b
2  neelam  3453256      c

# renaming columns

In [79]:
df1.rename( columns = {'name' : 'guyzz'} , inplace = True)
df1

    guyzz  salarry grades
0    arya    10000      a
1   parth    21342      b
2  neelam  3453256      c

# sorting data

#  -- if ascending is false then = decending 
#   -- ascending is true then = ascending

In [85]:
df1.sort_values(by='salarry',ascending=True)
df1

    guyzz  salarry grades
0    arya    10000      a
1   parth    21342      b
2  neelam  3453256      c

In [83]:
df1

    guyzz  salarry grades
0    arya    10000      a
1   parth    21342      b
2  neelam  3453256      c

In [87]:
df.isnull()

    name  salarry   city
0  False    False  False
1  False    False  False
2  False    False  False

# search null value

In [89]:
df.isnull()

,CustomerID,Name,Region,City,Plan,Amount,MonthlyUsage,Complaints,Recharged,Marks,Grade,Days_Since_Last_Recharge,Complaint_Type
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,True,True,True,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True,True,True,True

# fill value which is null

In [98]:
df.fillna(0, inplace=False)

,CustomerID,Name,Region,City,Plan,Amount,MonthlyUsage,Complaints,Recharged,Marks,Grade,Days_Since_Last_Recharge,Complaint_Type
0,101.0,Arya,Pune,Pune,Prepaid,250.0,320.0,Yes,Yes,85.0,A,12.0,Network Issue
1,102.0,Ravi,Delhi,Delhi,Postpaid,600.0,450.0,No,Yes,92.0,A+,8.0,Recharge Failed
2,103.0,Meera,Mumbai,Mumbai,Prepaid,150.0,210.0,No,No,78.0,B,45.0,Slow Internet
3,104.0,Kiran,Chennai,Chennai,Postpaid,450.0,500.0,Yes,Yes,88.0,A,3.0,SIM Not Working
4,105.0,Lina,Pune,Pune,Prepaid,300.0,330.0,No,Yes,90.0,A+,14.0,Network Issue
5,106.0,Soham,Delhi,Delhi,Prepaid,200.0,180.0,No,No,76.0,B,33.0,Billing Error
6,107.0,Riya,Kolkata,Kolkata,Postpaid,500.0,400.0,Yes,Yes,82.0,A,5.0,Network Issue
7,108.0,Rohan,Mumbai,Mumbai,Postpaid,400.0,390.0,No,Yes,87.0,A,25.0,Slow Internet
8,0.0,0,0,0,0,0.0,0.0,0,0,0.0,0,0.0,0
9,0.0,0,0,0,0,0.0,0.0,0,0,0.0,0,0.0,0
10,0.0,0,0,0,0,0.0,0.0,0,0,0.0,0,0.0,0
11,0.0,0,0,0,0,0.0,0.0,0,0,0.0,0,0.0,0
12,0.0,0,0,0,0,0.0,0.0,0,0,0.0,0,0.0,0
13,0.0,0,0,0,0,0.0,0.0,0,0,0.0,0,0.0,0
14,0.0,0,0,0,0,0.0,0.0,0,0,0.0,0,0.0,0
15,0.0,0,0,0,0,0.0,0.0,0,0,0.0,0,0.0,0
16,0.0,0,0,0,0,0.0,0.0,0,0,0.0,0,0.0,0
17,0.0,0,0,0,0,0.0,0.0,0,0,0.0,0,0.0,0
18,0.0,0,0,0,0,0.0,0.0,0,0,0.0,0,0.0,0